databaseType = "PostgreSql"
id = "46765814-77bf-41fe-aa53-5096beee9a3a"
name = "DemoS26Fly"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true
baselineVersion = "001_20251105111525"
baselineOnMigrate = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

  [[redgateCompare.staticDataTables]]
  schema = "public"
  table = "tipo_producto"

[environments.target2]
url = "jdbc:postgresql://d1088ea8-42f6-49a4-9273-aa8276eb473a.blijti4d0v0nkr55oei0.private.databases.appdomain.cloud:31949/flyway_test"
schemas = [ "public" ]
displayName = " Testing database"

[environments.target3]
url = "jdbc:postgresql://d1088ea8-42f6-49a4-9273-aa8276eb473a.blijti4d0v0nkr55oei0.private.databases.appdomain.cloud:31949/flyway_prod"
schemas = [ "public" ]
displayName = " Production database"

[environments.development]
url = "jdbc:postgresql://d1088ea8-42f6-49a4-9273-aa8276eb473a.blijti4d0v0nkr55oei0.private.databases.appdomain.cloud:31949/flyway_dev"
schemas = [ "public" ]
displayName = "Development database"

[environments.shadow]
url = "jdbc:postgresql://localhost:5432/flyway_shadow"
schemas = [ "public" ]
displayName = "Shadow database"
provisioner = "clean"
