databaseType = "PostgreSql"
id = "46765814-77bf-41fe-aa53-5096beee9a3a"
name = "DemoS26Fly"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true
baselineVersion = "001_20251105111525"
baselineOnMigrate = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

  [[redgateCompare.staticDataTables]]
  schema = "public"
  table = "tipo_producto"
